In [1]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.3.1 -> 25.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [3]:
sales = np.array([100, 200, 150, 300, 250, 400, 350])
print(sales)

[100 200 150 300 250 400 350]


In [4]:
store1_prices = np.array([10, 20, 30])
store2_prices = np.array([1, 2, 3])
result = store1_prices * store2_prices
print(result)

[10 40 90]


In [5]:
sales_january = np.array([300, 400])
sales_february = np.array([500, 600])
combined_sales = np.concatenate((sales_january, sales_february))
print(combined_sales) 

[300 400 500 600]


In [6]:
scores = np.array([[80, 90], [85, 95]])
flat_scores = scores.flatten()
print(flat_scores)

[80 90 85 95]


In [7]:
data = np.array([1, 2, 3, 4, 5, 6])
reshaped_data = data.reshape(2, 3)
print(reshaped_data)

[[1 2 3]
 [4 5 6]]
