In [8]:
import numpy as np

In [9]:
scores = np.array([
    [85, 90, 78, 92, 88],   # Student 1
    [72, 75, 80, 68, 74],   # Student 2
    [95, 88, 92, 96, 90],   # Student 3
    [60, 65, 70, 58, 62],   # Student 4
    [88, 84, 86, 89, 87]    # Student 5
])

In [10]:
student3_scores = scores[2]
print("Student 3 scores:", student3_scores)

Student 3 scores: [95 88 92 96 90]


In [11]:
subject2_scores = scores[:, 1]
print("Subject 2 scores:", subject2_scores)

Subject 2 scores: [90 75 88 65 84]


In [12]:
subset1 = scores[:3, :2]
print("First 3 students, first 2 subjects:\n", subset1)

First 3 students, first 2 subjects:
 [[85 90]
 [72 75]
 [95 88]]


In [13]:
subset2 = scores[-2:, -3:]
print("Last 2 students, last 3 subjects:\n", subset2)

Last 2 students, last 3 subjects:
 [[70 58 62]
 [86 89 87]]


In [14]:
bonus_scores = scores + 5
print("Scores after adding 5 bonus marks:\n", bonus_scores)


Scores after adding 5 bonus marks:
 [[ 90  95  83  97  93]
 [ 77  80  85  73  79]
 [100  93  97 101  95]
 [ 65  70  75  63  67]
 [ 93  89  91  94  92]]


In [15]:
scores[:, 3] -= 10
print("Scores after subtracting 10 from Subject 4:\n", scores)

Scores after subtracting 10 from Subject 4:
 [[85 90 78 82 88]
 [72 75 80 58 74]
 [95 88 92 86 90]
 [60 65 70 48 62]
 [88 84 86 79 87]]


In [16]:
percentage_scores = (scores / 100) * 100
print("Percentage scores:\n", percentage_scores)


Percentage scores:
 [[85. 90. 78. 82. 88.]
 [72. 75. 80. 58. 74.]
 [95. 88. 92. 86. 90.]
 [60. 65. 70. 48. 62.]
 [88. 84. 86. 79. 87.]]


In [17]:
average_scores = np.mean(scores, axis=1)
print("Average scores per student:", average_scores)

Average scores per student: [84.6 71.8 90.2 61.  84.8]


In [18]:
total_marks = np.sum(scores, axis=1)
print("Total marks per student:", total_marks)

Total marks per student: [423 359 451 305 424]


In [19]:
highest_score = np.max(scores)
print("Highest score in the array:", highest_score)


Highest score in the array: 95


In [20]:
average_per_subject = np.mean(scores, axis=0)
print("Average score per subject:", average_per_subject)


Average score per subject: [80.  80.4 81.2 70.6 80.2]


In [21]:
lowest_avg_student = np.argmin(average_scores) + 1  # Adding 1 to match student numbering
print("Student with lowest average score:", lowest_avg_student)

Student with lowest average score: 4
